### ISSUE TITLE
请问可以支持下视频鉴别么

### ISSUE THREAD

**Issue by uniteweiwei** [xiaoxuan6/aliyun-safe#3]
请问可以支持下视频鉴别么,自己改了一下,发现没有result了..

`
    public function checkVideo($video)
    {
        if(empty($video)){
            return null;
        }

        $request = new Green\VideoAsyncScanRequest();
        $request->setMethod("POST");
        $request->setAcceptFormat("JSON");

        if(is_string($video)){
            $task1 = array('dataId' =>  md5(uniqid()),
                           'url' => $video
            );
            $request->setContent(json_encode(array("tasks" => array($task1), "scenes" => array("porn","terrorism"))));
        }

        return $this->processResponse($request, $video, 'video');
    }
`

![image](https://user-images.githubusercontent.com/19373139/76510152-1e9c9a00-648c-11ea-9b70-688fdea3b351.png)

**Comment by xiaoxuan6** [comment]
> 
> 
> 请问可以支持下视频鉴别么,自己改了一下,发现没有result了..
> 
> `
> public function checkVideo($video)
> {
> if(empty($video)){
> return null;
> }
> 
> ```
>     $request = new Green\VideoAsyncScanRequest();
>     $request->setMethod("POST");
>     $request->setAcceptFormat("JSON");
> 
>     if(is_string($video)){
>         $task1 = array('dataId' =>  md5(uniqid()),
>                        'url' => $video
>         );
>         $request->setContent(json_encode(array("tasks" => array($task1), "scenes" => array("porn","terrorism"))));
>     }
> 
>     return $this->processResponse($request, $video, 'video');
> }
> ```
> 
> `
> 
> ![image](https://user-images.githubusercontent.com/19373139/76510152-1e9c9a00-648c-11ea-9b70-688fdea3b351.png)

目前不支持

**Comment by xiaoxuan6** [comment]
> 
> 
> 请问可以支持下视频鉴别么,自己改了一下,发现没有result了..
> 
> `
> public function checkVideo($video)
> {
> if(empty($video)){
> return null;
> }
> 
> ```
>     $request = new Green\VideoAsyncScanRequest();
>     $request->setMethod("POST");
>     $request->setAcceptFormat("JSON");
> 
>     if(is_string($video)){
>         $task1 = array('dataId' =>  md5(uniqid()),
>                        'url' => $video
>         );
>         $request->setContent(json_encode(array("tasks" => array($task1), "scenes" => array("porn","terrorism"))));
>     }
> 
>     return $this->processResponse($request, $video, 'video');
> }
> ```
> 
> `
> 
> ![image](https://user-images.githubusercontent.com/19373139/76510152-1e9c9a00-648c-11ea-9b70-688fdea3b351.png)

你这个是异步的不能实时返回检测结果需要你自己请求视频异步检测结果
我新开发了一个扩展包 `james.xue/laravel-ali-green` 这个支持视频检测

**Comment by uniteweiwei** [comment]
好的,谢谢,期待大大的开发包😄

**Comment by xiaoxuan6** [comment]
> 
> 
> 好的,谢谢,期待大大的开发包😄

已经开发好了，但是公司禁止外网，等周末我发布版本
